# PyTorch Training Configuration
model:
  input_dim: 3  # Set to 3 for torus data
  # hidden_dims: [32, 64, 32] # Removed as per new requirements
  num_hidden_layers: 8  # Fixed to 8 layers
  hidden_dim: 32  # Fixed to 32 neurons
  output_dim: 1  # Binary classification
  activation_fn_name: 'relu'
  output_activation_fn_name: 'sigmoid' # Output layer activation: 'sigmoid', 'softmax', 'none'
  dropout_rate: 0.15  # Slightly reduced dropout
  use_batch_norm: false

training:
  # General training settings
  device: 'mps'       # Using MPS for MacBook GPU
  epochs: 10  # Temporarily reduced for testin
  batch_size: 256    # Increased batch size for MPS
  learning_rate: 0.0005  # Reduced learning rate
  seed: 42            # Random seed for reproducibility

  # Optimizer settings (example: AdamW)
  optimizer:
    name: 'adamw'  # Using AdamW for better regularization
    weight_decay: 0.005  # Reduced weight decay

  # Loss function
  loss_fn: 'bce' # 'bce' (BinaryCrossEntropy), 'mse' (MeanSquaredError), 'cross_entropy' (CrossEntropyLoss for multi-class)

  # Learning rate scheduler (optional)
  lr_scheduler:
    type: 'reduce_on_plateau' # 'reduce_on_plateau', 'step_lr', 'none'
    factor: 0.2          # More aggressive reduction
    patience: 15         # Increased patience
    min_lr: 0.00001
    verbose: true        # Whether to print learning rate changes

  # Gradient clipping (optional)
  gradient_clipping:
    enabled: true
    max_norm: 0.5        # Reduced max norm

  # Early stopping (optional)
  early_stopping:
    enabled: true
    patience: 40         # Increased patience
    min_delta: 0.0001    # Minimum change in the monitored quantity to qualify as an improvement

  # Settings for vectorized and parallel training
  num_networks: 1000 # Number of networks to train (for torch_vectorised.py and torch_parallel.py)
  max_parallel_workers: null  # Will default to os.cpu_count()
  save_model_threshold: 0.8 # Optional: Minimum accuracy/metric to save a trained model

data:
  # General data loading and preprocessing settings
  type: 'synthetic'    # 'synthetic', 'csv', 'custom_function'
  path: null           # Path to data file if type is 'csv'
  synthetic_type: 'torus' # 'moons' or 'torus'
  noise: 0.05           # Reduced noise
  # For make_classification
  # n_features: 2
  # n_classes: 2
  # For make_regression
  # n_features_regression: 1
  # n_targets_regression: 1

  # Original data generation subsection to be preserved
  generation:
    n: 4000           # Number of points per torus
    big_radius: 3     # Radius of the larger circle of the torus
    small_radius: 1   # Radius of the smaller circle (tube) of the torus

  # Train/test split options
  split_ratio: 0.8     # Proportion of the dataset for the training set (e.g., 0.8 for 80% train)
                               # This replaces the old 'test_size' (0.2 test_size is 0.8 split_ratio)
  shuffle_data: true   # Whether to shuffle data before splitting
  random_seed_data: 42 # Random seed for data generation and splitting
                               # This replaces the old 'random_seed' for splitting consistency.

